# Default values for Configwatch.

image:
  repository: configwatch
  tag: stable
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
